name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: avaniklsjoshi/frontend-joshi@v0.1.0 # This is the action
        with:
          heroku_api_key: ${{secrets.1ca46010-1a80-4f71-8634-f1308822d07a}}
          heroku_app_name: "avanijoshi" #Must be unique in Heroku
          heroku_email: "avaniklsjoshi@gmail.com"
          healthcheck: "https://avanijoshi.herokuapp.com/health"
          usedocker: true
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: production
